title: Faizul Rakib Sayem
logo: /assets/img/Sayem.png
description: >
  <p align="center">
    <a href="https://www.linkedin.com/in/faizul-rakib-sayem-994b4837a/" target="_blank">LinkedIn</a> |
    <a href="https://scholar.google.com/citations?user=EVdrzM4AAAAJ&hl=en" target="_blank">Google Scholar</a> |
    <a href="https://github.com/Sayem13003" target="_blank">GitHub</a>
  </p>

  <p align="center">
    I am currently a 2nd year PhD student at the University of Central Florida. I am working on weak supervision and noise learning with vision-language modeling. My research interest lies in vision-language modeling, LLM, object hallucination mitigation, and alignment with human feedback.
  </p>

  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
github:
  is_project_page: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
